name: biorgm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - jupyter==1.1.1
    - matplotlib==3.10.7
    - numpy==2.3.5
    - pandas==2.3.3
    - pytorch-metric-learning==2.9.0
    - pyyaml==6.0.3
    - torch==2.8.0
    - torch-geometric==2.7.0
    - torchinfo==1.8.0
    - tqdm==4.67.1
    - rdkit==2025.9.1
    - rdkit-stubs==0.8
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - seaborn==0.13.2
    - wandb==0.23.0