[tool.ruff]
target-version = "py313"
line-length = 100
select = ["E", "F", "W", "C", "N", "I"]
# F401: Moduel imported but unused; F403: undable to detect undefined names
ignore = ["F401", "F403"]

[tool.pylance]
typeCheckingMode = "basic"
