"batch_size": 800
"dim_h": 128
"distance_metric": "cosine"
"dropout": 0.1
"encoder": "embedding"
"epochs": 5
"file_name": "pubchem_1k_triplets.csv"
"finetune": False # Do not evaluate model with finetuning tasks
"lr": 1.0e-6
"margin": 0.4
"num_samples_per_class": 4
"num_workers": 0
"task": "pretrain" # augmentation | pretrain | finetune
"type_of_triplets": "all"
"weight_decay": 5.0e-04
