name: biorgm
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - pytorch-cuda=12.1
  - pyg
  - pytorch-metric-learning
  - torchinfo
  - wandb
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - matplotlib
  - rdkit